import { TokenProvider } from "@/context/AuthToken";
import "./globals.css";
// import AuthGaurd from "@/context/AuthGuard";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <AuthGaurd> */}
        <TokenProvider>{children}</TokenProvider>
        {/* </AuthGaurd> */}
      </body>
    </html>
  );
}
